{% set name = "scikit-geometry" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/scikit-geometry/{{ name }}/archive/{{ version }}.tar.gz
  sha256: dd071709c14763756c0040d806f7dba5e86358ebcb44518151cff6491446b14e
  patches:
    - osx_cpp14.patch  # [osx]

build:
  number: 1
  skip: true  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp 5.0
  run:
    - python
    - cgal-cpp 5.0
    - matplotlib-base

test:
  imports:
    - skgeom
    - skgeom.draw

about:
  home: https://github.com/scikit-geometry/scikit-geometry
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Scientific Python Geometric Algorithms Library
  doc_url: https://scikit-geometry.github.io/scikit-geometry
  dev_url: https://github.com/scikit-geometry/scikit-geometry

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
