{% set name = "scikit-geometry" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/scikit-geometry/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1f49fe69754c74d644e37f343f28f302c022b1a10fcf8cfd5326eccfa83e0b41
  patches:
    - osx_cpp14.patch  # [osx]

build:
  number: 1
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python 3
    - pybind11
    - cgal-cpp
    - cgal
  run:
    - python 3
    - cgal-cpp
    - cgal
    - vs2015_runtime  # [win]
    - mpir  # [win]
    - mpfr
    - gmp  # [not win]
    - cgal-cpp
    - boost-cpp
    - matplotlib-base

test:
  imports:
    - skgeom
    - skgeom.draw

about:
  home: https://github.com/scikit-geometry/scikit-geometry
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Scientific Python Geometric Algorithms Library
  doc_url: https://scikit-geometry.github.io/scikit-geometry
  dev_url: https://github.com/scikit-geometry/scikit-geometry

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
